apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reactive
commonLabels:
  app.kuernetes.io/name: student
resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
generatorOptions:
  disableNameSuffixHash: true