apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reactive
commonLabels:
  app.kubernetes.io/name: student
secretGenerator:
  - name: ingress-basic-auth
    type: Opaque
    files:
    - auth
generatorOptions:
  disableNameSuffixHash: true
resources:
  - student-ingress.yaml